env:
  browser: true
  es2021: true
  jest: true
extends:
  - standard
overrides: [ ]
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "semi": [ "error", "always" ],
  "comma-dangle": [ "error", "always-multiline" ],
  "quotes": [ "error", "single" ],
  "no-unused-vars": [ "error", { "vars": "all", "args": "all", "ignoreRestSiblings": false, "argsIgnorePattern": "^_" } ],
#  "no-unused-vars": "off",
}
