name: Run tests
on:
  pull_request
jobs:
  test-express-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: [4.4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Use MongoDB ${{ matrix.mongodb-version }}
        uses:
          supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: CI=true npm test

      - name: Run linter
        run: npm run lint

      - name: Start server
        run: npm start &

      - name: Check if server is up
        run: curl localhost:3001/health | grep "OK"
